baseURL: https://jefebromden.github.io
languageCode: en-us
title: JefeBromden
theme: LoveIt

params:
  title: Weekly Thoughts
  description: My notes on Open Source, Language and Science

  header:
    title:
      name: JefeBromden
  footer:
    # Inject invisible Mastodon rel="me" link
    mastodonRelme: true

  home:
    profile:
      title: JefeBromden
      subtitle: Your life in The Shell

  social:
    Mastodon: https://mastodon.social/@jefebromden
