baseURL = 'https://jefebromden.github.io'
languageCode = 'en-us'
title = 'JefeBromden'
theme = 'LoveIt'

[params.header.title]
  name = 'JefeBromden'

[params.home.profile]
  title = 'JefeBromden'
  subtitle = 'Your life in The Shell'
